In [2]:
using Revise
using BilevelTrajOpt

In [212]:
# test the solution
function f(x)
    return x[1] * x[4] * (x[1] + x[2] + x[3]) + x[3]
end

function h(x)
    return [40. - (x[1]^2 + x[2]^2 + x[3]^2 + x[4]^2)]
end

function g(x)
#     gx = [25. - (x[1]*x[2]*x[3]*x[4])]
#     gx = vcat(gx, 1. - x)
#     gx = vcat(gx, x - 5.)
    gx = [0.]
    return gx
end

x0 = [1., 5., 5., 1.]
λ0 = ones(1)
# μ0 = ones(1+2*length(x0))
μ0 = [1.]
num_steps = 100
c_vect = [2.^i for i = 1:num_steps]
x_sol, λ_sol, μ_sol = auglag_solve(x0,λ0,μ0,f,h,g,c_vect)

num_h = length(λ0)
num_g = length(μ0)
x_sol_ip = ip_solve(x0,f,h,g,num_h,num_g)

x_sol_known = [1.000, 4.743, 3.821, 1.379]

display(x_sol)
display(x_sol_ip)
display(x_sol_known)

148.0

12.38349950180343

4-element Array{Float64,1}:
  58.0
 231.0
 232.0
  57.0

"---"

18.949847839827616

6.634795540845462

4-element Array{Float64,1}:
 20.5483
 77.1883
 77.8212
 20.0862

"---"

6.6948623661011295

4.797129242584325

4-element Array{Float64,1}:
  6.25116
 12.6974 
 13.4733 
  5.65576

"---"

5.182977442717013

4.222928777281592

4-element Array{Float64,1}:
  2.47569
 46.7716 
 43.3539 
  2.45417

"---"

4.2243033830662835

13.899480418055735

4-element Array{Float64,1}:
 0.401911
 3.97833 
 4.51835 
 0.949634

"---"

24.27725878313895

3.484394751573923

4-element Array{Float64,1}:
   0.567673
 549.423   
 363.994   
   1.18897 

"---"

3.4883885295596966

3.6984689656763012

4-element Array{Float64,1}:
  0.10445  
 15.1064   
 10.9528   
  0.0622259

"---"

4.161182502509877

3.215344004931659

4-element Array{Float64,1}:
   0.157891 
 236.914    
 141.868    
   0.0372336

"---"

3.215361351878986

6971.9271328759205

4-element Array{Float64,1}:
 -0.00382753
  2.05308   
  2.21209   
  0.0320304 

"---"

13942.606048398638

91.16029090252106

4-element Array{Float64,1}:
     3.31716
 70613.9    
 13340.4    
     1.35258

"---"

181.14054800242795

1.1840791224366942

4-element Array{Float64,1}:
     0.504506
 10727.0     
  2027.25    
     0.206931

"---"

1.1947747799378468

1.1407322645193358

4-element Array{Float64,1}:
   0.00857911
 164.545     
  32.0659    
   0.00525978

"---"

1.1445995011494932

1.1087657556096364

4-element Array{Float64,1}:
   0.00661042
 140.075     
  26.5955    
   0.00295478

"---"

1.1236676597299162

1.0788187298665257

4-element Array{Float64,1}:
   0.0183317 
 389.347     
  69.3682    
  -0.00143411

"---"

1.0793208059678527

1.241330063477046

4-element Array{Float64,1}:
   0.00435944 
 101.11       
  18.4951     
   0.000741797

"---"

1.4641912708747054

1.0164074706504462

4-element Array{Float64,1}:
    0.212458
 3017.6     
  493.34    
   -0.138793

"---"

1.0164080567210758

41171.263390507534

4-element Array{Float64,1}:
 -0.0016845 
  6.92051   
  2.12683   
  0.00292205

"---"

82342.3890843929

17.177831889008647

4-element Array{Float64,1}:
    -3.19845  
     2.65348e6
 57221.2      
    16.9277   

"---"

34.219294419436395

0.13626789251106927

4-element Array{Float64,1}:
    -0.0908953
 75611.8      
  1631.48     
     0.482315 

"---"

0.13626945370498342

763.4491005222712

4-element Array{Float64,1}:
  0.000221459
 32.3607     
  1.69739    
  0.000157085

"---"

1526.9572382417741

-0.05823599118823356

4-element Array{Float64,1}:
    15.3148   
     1.01274e6
 -9448.46     
   -12.9133   

"---"

-0.05745665943503083

-0.0626210340945635

4-element Array{Float64,1}:
    0.0213674
 1446.31     
  -12.4963   
   -0.0178441

"---"

-0.061854451539513085

-0.06610871960411942

4-element Array{Float64,1}:
    0.0308884
 2028.58     
  -19.3324   
   -0.0261153

"---"

-0.06571258329877286

-0.06882941192776253

4-element Array{Float64,1}:
    0.0319408
 2062.28     
  -20.6868   
   -0.0271828

"---"

-0.06808770875955211

-0.07104984177684696

4-element Array{Float64,1}:
    0.0633517
 3990.74     
  -42.9014   
   -0.0543999

"---"

-0.07094405657613886

-0.07152227478547722

4-element Array{Float64,1}:
    0.0338695
 2131.4      
  -22.9812   
   -0.0290949

"---"

-0.0689221612272845

-0.07454336371408596

4-element Array{Float64,1}:
     0.244723
 14943.8     
  -174.15    
    -0.21237 

"---"

-0.07454121163927664

1.4856180211874659

4-element Array{Float64,1}:
   0.00943765
 608.007     
  -6.16687   
  -0.00804315

"---"

3.0561815114309243

-0.08495396211367104

4-element Array{Float64,1}:
    12.8195   
     7.34538e5
 -9865.49     
   -11.3339   

"---"

-0.08495396209023111

3.3094873160961766e9

4-element Array{Float64,1}:
 -0.000538849
  4.01309    
  0.94609    
  0.000626745

"---"

6.618974633852861e9

1.1778778081346164e7

4-element Array{Float64,1}:
  2.12913e5 
  6.7211e10 
 -1.77071e10
 -1.68695e5 

"---"

2.3557557776056208e7

88.45265302459822

4-element Array{Float64,1}:
  17453.3      
      5.50955e9
     -1.45152e9
 -13828.6      

"---"

178.51656595838526

-1.6112560476902962

4-element Array{Float64,1}:
  68.1632   
   2.15174e7
  -5.66886e6
 -54.007    

"---"

-1.611256045018124

13920.127455441296

4-element Array{Float64,1}:
   0.000455927
 165.753      
 -42.6683     
  -0.000328755

"---"

27841.90066973431

-1.6457168104052087

4-element Array{Float64,1}:
  1967.02     
     5.3425e8 
    -1.43979e8
 -1665.14     

"---"

-1.6457009467667294

-1.6458577381048867

4-element Array{Float64,1}:
     0.0938161
 25503.9      
 -6872.23     
    -0.0793899

"---"

-1.645759574475446

-1.6460180717501334

4-element Array{Float64,1}:
      0.330549
  89720.4     
 -24181.9     
     -0.279892

"---"

-1.6460167899122928

-1.6426535879272266

4-element Array{Float64,1}:
     0.0533609
 14499.3      
 -3907.24     
    -0.045164 

"---"

-1.6388951836343018

-1.6464171157701428

4-element Array{Float64,1}:
  4.09911  
  1.1103e6 
 -2.99353e5
 -3.47377  

"---"

-1.6464171155510858

32171.15913662923

4-element Array{Float64,1}:
    0.00131437
  379.08      
 -101.206     
   -0.00108553

"---"

64343.979707679835

-1.661428074408628

4-element Array{Float64,1}:
  25556.1      
      6.49267e9
     -1.76768e9
 -22143.5      

"---"

-1.6614267505611497

-1.6613062293190672

4-element Array{Float64,1}:
      0.231744
  58899.5     
 -16034.8     
     -0.200772

"---"

-1.6610866028080824

-1.66153114697968

4-element Array{Float64,1}:
  4.22457  
  1.07287e6
 -2.92114e5
 -3.6609   

"---"

-1.661531142987851

4.376784120319478

4-element Array{Float64,1}:
     0.0253793
  6468.55     
 -1760.22     
    -0.0219668

"---"

10.41597769211584

-1.6624094502240179

4-element Array{Float64,1}:
  1406.18     
     3.55802e8
    -9.69309e7
 -1220.04     

"---"

-1.6624094502240143

1.9911262976770112e12

4-element Array{Float64,1}:
 -4.46663e-5
 12.2043    
 -2.32482   
  6.52243e-5

"---"

3.982252595356156e12

7.768056889356452e7

4-element Array{Float64,1}:
 -7.77375e8 
  4.00015e14
 -1.42825e14
  8.61699e8 

"---"

1.553611399138401e8

-2.066393837236783

4-element Array{Float64,1}:
 -6.84653e6 
  3.52303e12
 -1.2579e12 
  7.58919e6 

"---"

-2.0061045482493776

-2.126683163734489

4-element Array{Float64,1}:
 -269.739    
    1.388e8  
   -4.95585e7
  298.998    

"---"

-2.126683163734489

2.795443241495795e12

4-element Array{Float64,1}:
  4.91364e-5 
 -1.48519e-10
  1.0        
 -4.43282e-5 

"---"

5.590886482993466e12

9.703253439451411e6

4-element Array{Float64,1}:
  4.57714e8 
  1.9186e15 
 -5.95581e14
 -3.16151e8 

"---"

1.9406508753937274e7

-1.8749734747572435

4-element Array{Float64,1}:
  1.20493e6 
  5.0507e12 
 -1.56786e12
 -8.32264e5 

"---"

-1.8749146760880282

-1.8750325867034088

4-element Array{Float64,1}:
  4.19469  
  1.75829e7
 -5.45817e6
 -2.89734  

"---"

-1.8750325866522497

33.18489059277434

4-element Array{Float64,1}:
     0.00552927
 23194.4       
 -7199.13      
    -0.00381603

"---"

68.24505232192158

-1.8752711351133136

4-element Array{Float64,1}:
  6482.99      
     2.71543e10
    -8.43055e9 
 -4481.58      

"---"

-1.8752711351133136

1.6133934314867735e8

4-element Array{Float64,1}:
 -4.15185e-6 
 -1.43755e-12
  1.0        
  6.006e-6   

"---"

3.2267868816481334e8

-1.8669489742606256

4-element Array{Float64,1}:
 -1.66589e6 
  1.16549e14
 -3.60194e13
 -4.41656e6 

"---"

-1.8664408754994237

-1.8674570918698816

4-element Array{Float64,1}:
  -4.18085  
   2.925e8  
  -9.03971e7
 -11.0842   

"---"

-1.8674570918480538

6.322201883006421

4-element Array{Float64,1}:
      0.00106035
 -74251.1       
  22948.3       
      0.00281335

"---"

14.511812936828285

-1.8673873373336107

4-element Array{Float64,1}:
 -1062.54      
     7.42701e10
    -2.29523e10
 -2814.81      

"---"

-1.8673873372462992

-1.6952472663822284

4-element Array{Float64,1}:
     0.00424813
    -2.97005e5 
 91786.8       
     0.011256  

"---"

-1.5231196449010334

-1.8673685575617591

4-element Array{Float64,1}:
 -308.151     
    2.15345e10
   -6.65489e9 
 -816.174     

"---"

NaN

NaN

4-element Array{Float64,1}:
 -9.56206e-7 
  1.98027e-14
  1.0        
 -3.61021e-7 

"---"

NaN

NaN

4-element Array{Float64,1}:
  -987.065     
    -4.54909e11
     1.40578e11
 -1074.73      

"---"

NaN

NaN

4-element Array{Float64,1}:
  5.96058e-8 
  5.75734e-37
 -3.03052e-6 
  5.47437e-8 

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0        
 5.75734e-37
 0.0        
 0.0        

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

NaN

NaN

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

"---"

4-element Array{Float64,1}:
 0.0        
 0.0        
 1.32831e-11
 0.0        

4-element Array{Float64,1}:
 -4.56763
 -1.66137
 -1.7612 
 -3.64345

4-element Array{Float64,1}:
 1.0  
 4.743
 3.821
 1.379

Solve_Succeeded


In [ ]:
# test the gradient