In [2]:
using Revise
using BilevelTrajOpt

In [107]:
# test the solution
function f(x)
    return x[1] * x[4] * (x[1] + x[2] + x[3]) + x[3]
end

function h(x)
    return [40. - (x[1]^2 + x[2]^2 + x[3]^2 + x[4]^2)]
end

function g(x)
    gx = [25. - (x[1]*x[2]*x[3]*x[4])]
    gx = vcat(gx, 1. - x)
    gx = vcat(gx, x - 5.)
    return gx
end

x0 = [1., 5., 5., 1.]
λ0 = ones(1)
μ0 = ones(1+2*length(x0))
num_steps = 10
α_vect = [1.^i for i = 1:num_steps]
c_vect = [2.^i for i = 1:num_steps]
x_sol, λ_sol, μ_sol = auglag_solve(x0,λ0,μ0,f,h,g,α_vect,c_vect)

num_h = 1
num_g = 1+2*length(x0)
x_sol_ip = ip_solve(x0,f,h,g,num_h,num_g)

x_sol_known = [1.000, 4.743, 3.821, 1.379]

display(x_sol)
display(x_sol_ip)
display(x_sol_known)

4-element Array{Float64,1}:
 -0.00237116
  4.4357    
  4.49981   
 -0.00244711

4-element Array{Float64,1}:
 1.0    
 4.743  
 3.82115
 1.37941

4-element Array{Float64,1}:
 1.0  
 4.743
 3.821
 1.379

Solve_Succeeded


In [ ]:
# test the gradient