In [1]:
using Revise
using BilevelTrajOpt

In [ ]:
a = rand(4)
A = diagm(a)

In [ ]:
# test the solution
function f(x)
#     return 0.
#     return x[1] * x[4] * (x[1] + x[2] + x[3]) + x[3]
#     return x'*A*x 
    return sum(x)
end

function h(x)
#     return [40. - (x[1]^2 + x[2]^2 + x[3]^2 + x[4]^2)]
#     return [x[1] + x[2] - 1., x[3] - 1., x[4]*x[1]]
    return [6. - x[1],x[1]*x[2],x[1]*.5+x[3]-4.]
end

function g(x)
#     return [25. - (x[1]*x[2]*x[3]*x[4])]
#     return vcat([25. - (x[1]*x[2]*x[3]*x[4])], 1. - x, x - 5.)
#     return vcat([1. - x[2]],-x)
#     return vcat(-x[2:3],5.-x[4])    
#     return [0.]
#     return vcat([x[1] - .1], 5. - x[4])
    return vcat(-x[2:3],5.-x[4],10.-x[4],17.-x[4],5-x[1]*x[4])
end

x0 = zeros(4)
λ0 = zeros(length(h(x0)))
μ0 = zeros(length(g(x0)))
c0 = 1.

# x0 = x_sol
# λ0 = λ_sol
# μ0 = μ_sol
# c0 = c_sol

x_sol, λ_sol, μ_sol, c_sol = auglag_solve(x0,λ0,μ0,f,h,g,c0=c0)

num_h = length(λ0)
num_g = length(μ0)
x_sol_ip = ip_solve(x0,f,h,g,num_h,num_g)

# x_sol_known = [1.000, 4.743, 3.821, 1.379]

display(x_sol)
display(x_sol_ip)
# display(x_sol_known)

In [ ]:
x = x_sol
display(f(x))
display(h(x))
display(g(x))

x = x_sol_ip
display(f(x))
display(h(x))
display(g(x))

In [5]:
# test the gradient
function solve_prob(z)
    function f(x)
#         return x'*A*x + z[1]
        return sum(x)
    end

    function h(x)
#         return [x[1] + x[2] - 1., x[3] - z[2], x[4]*x[1]]
        return [z[1] - x[1],x[1]*x[2],x[1]*.5+x[3]-z[2]]
    end

    function g(x)
#         return vcat([x[1] - z[4]], z[3] - x[4])
        return vcat(-x[2:3],z[3]-x[4],10.-x[4],z[4]-x[4],5-x[1]*x[4])
    end

    x0 = zeros(4)
    λ0 = zeros(length(h(x0)))
    μ0 = zeros(length(g(x0)))

#     x_sol_ip = ip_solve(x0,f,h,g,length(h(x0)),length(g(x0)))
#     display(x_sol_ip)
    
    x_sol, λ_sol, μ_sol, c_sol = auglag_solve(x0,λ0,μ0,f,h,g)
    display(x_sol)

    x_sol
end

solve_prob (generic function with 1 method)

In [6]:
# z0 = [2.,-1.,0.,1.]
z0 = [6.,4.,5.,17.]

sol = solve_prob(z0)

# autodiff 
J_auto = ForwardDiff.jacobian(solve_prob,z0)

# # numerical
ϵ = 1e-8
J_num = zeros(size(J_auto))
for i = 1:length(z0)
    δ = zeros(length(z0))
    δ[i] = ϵ
    J_num[:,i] = (solve_prob(z0 + δ) - sol)/ϵ
end

display("----")
display(sol)
display(J_auto)
display(J_num)

4-element Array{Float64,1}:
  6.0       
 -1.7713e-13
  1.0       
 17.0       

4-element Array{ForwardDiff.Dual{ForwardDiff.Tag{#solve_prob,Float64},Float64,4},1}:
 Dual{ForwardDiff.Tag{#solve_prob,Float64}}(6.0,1.0,2.50774e-12,-7.17301e-14,2.12469e-9)                  
 Dual{ForwardDiff.Tag{#solve_prob,Float64}}(-3.89208e-13,4.80778e-11,9.17612e-15,-3.27458e-14,1.28686e-11)
 Dual{ForwardDiff.Tag{#solve_prob,Float64}}(1.0,-0.5,1.0,1.08466e-13,-1.1214e-9)                          
 Dual{ForwardDiff.Tag{#solve_prob,Float64}}(17.0,-1.41349e-8,-3.74774e-9,1.23179e-8,1.0)                  

4-element Array{Float64,1}:
  6.0        
 -2.99311e-13
  1.0        
 17.0        

4-element Array{Float64,1}:
  6.0        
  1.86764e-14
  1.0        
 17.0        

4-element Array{Float64,1}:
  6.0        
  1.92102e-13
  1.0        
 17.0        

4-element Array{Float64,1}:
  6.0        
 -4.72648e-13
  1.0        
 17.0        

"----"

4-element Array{Float64,1}:
  6.0       
 -1.7713e-13
  1.0       
 17.0       

4×4 Array{Float64,2}:
  1.0           2.50774e-12  -7.17301e-14   2.12469e-9 
  4.80778e-11   9.17612e-15  -3.27458e-14   1.28686e-11
 -0.5           1.0           1.08466e-13  -1.1214e-9  
 -1.41349e-8   -3.74774e-9    1.23179e-8    1.0        

4×4 Array{Float64,2}:
  1.00013      -0.000112799   0.000404921  -0.000287503
 -1.22181e-5    1.95806e-5    3.69231e-5   -2.95519e-5 
 -0.49988       1.0009       -0.000132094   0.000680089
 -0.000140332  -0.000106581  -0.000719425   0.999975   