In [1]:
using Revise
using BilevelTrajOpt

using RigidBodyDynamics
using MeshCatMechanisms
using ForwardDiff

┌ Info: Precompiling BilevelTrajOpt [9688c538-179f-11e9-3174-495cea6b7f67]
└ @ Base loading.jl:1187


HTML{String}("    <script class='js-collapse-script'>\n        var curMatch =\n            window.location.href\n            .match(/(.*?)\\/notebooks\\/.*\\.ipynb/);\n\n        curMatch = curMatch ||\n            window.location.href\n            .match(/(.*?)\\/apps\\/.*\\.ipynb/);\n\n        if ( curMatch ) {\n            \$('head').append('<base href=\"' + curMatch[1] + '/\">');\n        }\n    </script>\n")

HTML{String}("<script class='js-collapse-script' src='/assetserver/b464848323e0a4c9a3cfe11f8edca2932188b6d9-assets/webio/dist/bundle.js'></script>")

HTML{String}("<script class='js-collapse-script' src='/assetserver/b464848323e0a4c9a3cfe11f8edca2932188b6d9-assets/providers/ijulia_setup.js'></script>")

HTML{String}("  <script class='js-collapse-script'>\n    \$('.js-collapse-script').parent('.output_subarea').css('padding', '0');\n  </script>\n")

┌ Warning: `using A: B` will only be allowed for single bindings, not modules. Use `using A.B` instead
│   caller = ip:0x0
└ @ Core :-1


In [53]:
urdf = joinpath("..", "urdf", "panda", "panda_arm_plate.urdf")
mechanism = parse_urdf(Float64, urdf)

Spanning tree:
Vertex: world (root)
  Vertex: panda_link0, Edge: panda_link0_to_world
    Vertex: panda_link1, Edge: panda_joint1
      Vertex: panda_link2, Edge: panda_joint2
        Vertex: panda_link3, Edge: panda_joint3
          Vertex: panda_link4, Edge: panda_joint4
            Vertex: panda_link5, Edge: panda_joint5
              Vertex: panda_link6, Edge: panda_joint6
                Vertex: panda_link7, Edge: panda_joint7
                  Vertex: panda_link8, Edge: panda_joint8
No non-tree joints.

In [54]:
mvis = MechanismVisualizer(mechanism, URDFVisuals(urdf));

In [55]:
IJuliaCell(mvis)

WebIO.Scope("scope-d3f930dd-5cb0-47a7-b07b-689730422443", WebIO.Node{WebIO.DOM}(WebIO.DOM(:html, :div), Any[Node{DOM}(DOM(:html, :iframe), Any[], Dict{Symbol,Any}(:attributes=>Dict{String,Any}("height"=>"100%","scrolling"=>"no","src"=>"javascript:void(0)","frameborder"=>0),:id=>"ifr",:style=>Dict("width"=>"100%","flexGrow"=>"1")), 0)], Dict{Symbol,Any}(:style=>Dict("flexDirection"=>"column","height"=>"100%","minHeight"=>"400px","display"=>"flex","width"=>"100%","overflow"=>"hidden")), 1), Dict{String,Tuple{Observables.AbstractObservable,Union{Nothing, Bool}}}(), Set(String[]), nothing, Any[], Dict{Any,Any}("_promises"=>Dict{Any,Any}("importsLoaded"=>Any[JSString("function () {\n    var frame = this.dom.querySelector(\"#ifr\");\n    var doc = frame.contentDocument\n    var win = frame.contentWindow\n\n    // Ensure that the iframe's baseURI matches the baseURI of the\n    // outer document. This is necessary to resolve\n    // https://github.com/JuliaGizmos/WebIO.jl/issues/167\n    var base = doc.createElement(\"base\");\n    base.setAttribute(\"href\", document.baseURI);\n    doc.head.appendChild(base);\n\n    var webio = doc.createElement(\"script\")\n    webio.src = \"/assetserver/b464848323e0a4c9a3cfe11f8edca2932188b6d9-assets/webio/dist/bundle.js\"\n    var parent = window\n\n    function resizeIframe() {\n        doc.body.style.padding = '0'\n        doc.body.style.margin = '0'\n        doc.documentElement.height = '100%'\n        doc.body.height = '100%'\n    }\n\n    webio.onload = function () {\n        win.WebIO.sendCallback = parent.WebIO.sendCallback; // Share stuff\n        win.WebIO.scopes = parent.WebIO.scopes\n        win.WebIO.obsscopes = parent.WebIO.obsscopes\n        win.WebIO._connected = true\n        doc.body.innerHTML = \"<html><body>\" + \"<div class='display:none'></div><unsafe-script style='display:none'>\\nWebIO.mount(this.previousSibling,{&quot;props&quot;:{},&quot;nodeType&quot;:&quot;Scope&quot;,&quot;type&quot;:&quot;node&quot;,&quot;instanceArgs&quot;:{&quot;imports&quot;:{&quot;data&quot;:[{&quot;name&quot;:null,&quot;type&quot;:&quot;js&quot;,&quot;url&quot;:&quot;/assetserver/4e6dc072e028c3b44a2abd252ef43801b1ba6ad7-main.min.js&quot;}],&quot;type&quot;:&quot;async_block&quot;},&quot;id&quot;:&quot;scope-0271d208-d443-4194-8b57-212131d50ee8&quot;,&quot;handlers&quot;:{&quot;meshcat-command&quot;:[(function (val){return this.viewer.handle_command_message({&quot;data&quot;:val})})],&quot;_promises&quot;:{&quot;importsLoaded&quot;:[(function (mc){var element=this.dom.children[0]; this.viewer=new mc.Viewer(element); WebIO.setval({&quot;name&quot;:&quot;meshcat-request&quot;,&quot;scope&quot;:&quot;scope-0271d208-d443-4194-8b57-212131d50ee8&quot;,&quot;id&quot;:&quot;ob_60&quot;,&quot;type&quot;:&quot;observable&quot;},String(Date.now())); window.document.body.style.margin=&quot;0&quot;; return window.meshcat_viewer=this.viewer})]}},&quot;systemjs_options&quot;:null,&quot;observables&quot;:{&quot;meshcat-command&quot;:{&quot;sync&quot;:false,&quot;id&quot;:&quot;ob_59&quot;,&quot;value&quot;:[131,166,109,97,116,114,105,120,199,64,23,0,0,128,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,128,63,164,116,121,112,101,173,115,101,116,95,116,114,97,110,115,102,111,114,109,164,112,97,116,104,218,0,122,47,109,101,115,104,99,97,116,47,119,111,114,108,100,47,112,97,110,100,97,95,108,105,110,107,48,47,112,97,110,100,97,95,108,105,110,107,49,47,112,97,110,100,97,95,108,105,110,107,50,47,112,97,110,100,97,95,108,105,110,107,51,47,112,97,110,100,97,95,108,105,110,107,52,47,112,97,110,100,97,95,108,105,110,107,53,47,112,97,110,100,97,95,108,105,110,107,54,47,112,97,110,100,97,95,108,105,110,107,55,47,112,97,110,100,97,95,108,105,110,107,56]},&quot;meshcat-controls&quot;:{&quot;sync&quot;:true,&quot;id&quot;:&quot;ob_61&quot;,&quot;value&quot;:[]},&quot;meshcat-request&quot;:{&quot;sync&quot;:true,&quot;id&quot;:&quot;ob_60&quot;,&quot;v

In [56]:
widget = manipulate!(mvis)

Widgets.Widget{:rbd_manipulator,Any}(OrderedCollections.OrderedDict{Symbol,Any}(:panda_link0_to_world=>Widget{:rbd_joint,Any}(OrderedCollections.OrderedDict{Symbol,Any}(), Observable{Any} with 1 listeners. Value:
nothing, nothing, defaultlayout),:panda_joint1=>Widget{:rbd_joint,Any}(OrderedCollections.OrderedDict{Symbol,Any}(:q1=>Widget{:slider,Float64}(OrderedCollections.OrderedDict{Symbol,Any}(:changes=>Observable{Int64} with 1 listeners. Value:
0,:index=>Observable{Any} with 2 listeners. Value:
315,:formatted_vals=>Observable{Any} with 1 listeners. Value:
["-3.14159", "-3.13159", "-3.12158", "-3.11158", "-3.10157", "-3.09157", "-3.08156", "-3.07156", "-3.06155", "-3.05155"  …  "3.05155", "3.06155", "3.07156", "3.08156", "3.09157", "3.10157", "3.11158", "3.12158", "3.13159", "3.14159"],:formatted_value=>Observable{String} with 1 listeners. Value:
"0.0",:value=>Observable{Float64} with 2 listeners. Value:
0.0), Observable{Float64} with 2 listeners. Value:
0.0, Scope("knockout-component-223f2a1a-68df-402d-8718-cbc02a817bde", Node{DOM}(DOM(:html, :div), Any[Node{DOM}(DOM(:html, :div), Any[Node{DOM}(DOM(:html, :label), Any["panda_joint1.q1"], Dict{Symbol,Any}(:className=>"interact ",:style=>Dict{Any,Any}(:padding=>"5px 10px 0px 10px")), 1)], Dict{Symbol,Any}(:attributes=>Dict("class"=>"interact-flex-row-left")), 2), Node{DOM}(DOM(:html, :div), Any[Node{DOM}(DOM(:html, :input), Any[], Dict{Symbol,Any}(:max=>629,:min=>1,:attributes=>Dict{Any,Any}(:type=>"range",Symbol("data-bind")=>"numericValue: index, valueUpdate: 'input', event: {change : function () {this.changes(this.changes()+1)}}","orient"=>"horizontal"),:step=>1,:className=>"slider slider is-fullwidth",:style=>Dict{Any,Any}()), 0)], Dict{Symbol,Any}(:attributes=>Dict("class"=>"interact-flex-row-center")), 1), Node{DOM}(DOM(:html, :div), Any[Node{DOM}(DOM(:html, :p), Any[], Dict{Symbol,Any}(:attributes=>Dict("data-bind"=>"text: formatted_value")), 0)], Dict{Symbol,Any}(:attributes=>Dict("class"=>"interact-flex-row-right")), 1)], Dict{Symbol,Any}(:attributes=>Dict("class"=>"interact-flex-row")), 7), Dict{String,Tuple{Observables.AbstractObservable,Union{Nothing, Bool}}}("formatted_vals"=>(Observable{Any} with 1 listeners. Value:
["-3.14159", "-3.13159", "-3.12158", "-3.11158", "-3.10157", "-3.09157", "-3.08156", "-3.07156", "-3.06155", "-3.05155"  …  "3.05155", "3.06155", "3.07156", "3.08156", "3.09157", "3.10157", "3.11158", "3.12158", "3.13159", "3.14159"], nothing),"changes"=>(Observable{Int64} with 1 listeners. Value:
0, nothing),"formatted_value"=>(Observable{String} with 1 listeners. Value:
"0.0", nothing),"index"=>(Observable{Any} with 2 listeners. Value:
315, nothing)), Set(String[]), nothing, Any["knockout"=>"/home/blandry/.julia/packages/Knockout/JIqpG/src/../assets/knockout.js", "knockout_punches"=>"/home/blandry/.julia/packages/Knockout/JIqpG/src/../assets/knockout_punches.js", "/home/blandry/.julia/packages/InteractBase/3SqBl/src/../assets/style.css"], Dict{Any,Any}("formatted_vals"=>Any[JSString("(function (val){return (val!=this.model[\"formatted_vals\"]()) ? (this.valueFromJulia[\"formatted_vals\"]=true, this.model[\"formatted_vals\"](val)) : undefined})")],"_promises"=>Dict{Any,Any}("importsLoaded"=>Any[JSString("function (ko, koPunches) {\n    ko.punches.enableAll();\n    ko.bindingHandlers.numericValue = {\n        init : function(element, valueAccessor, allBindings, data, context) {\n            var stringified = ko.observable(ko.unwrap(valueAccessor()));\n            stringified.subscribe(function(value) {\n                var val = parseFloat(value);\n                if (!isNaN(val)) {\n                    valueAccessor()(val);\n                }\n            })\n            valueAccessor().subscribe(function(value) {\n                var str = JSON.stringify(value);\n                if ((str == \"0\") && ([\"-0\", \"-0.\"].indexOf(stringified()) >= 0))\n                     return;\n                 if ([\"null\", \"\"].indexOf(str) >= 0)\n            

In [ ]:
open(mvis)

In [5]:
env = parse_contacts(mechanism, urdf, [])
x0 = MechanismState(mechanism)
Δt = 0.05
N = 10
traj_data = get_traj_data(mechanism,env,Δt,N,false);

In [11]:
x_start = zeros(traj_data.num_q+traj_data.num_v)
x_start[2] = -pi/2
x_start[6] = pi/2
add_state_eq!(traj_data, xi -> xi - x_start, 1)

x_goal = zeros(traj_data.num_q+traj_data.num_v)
x_goal[2] = pi/2
x_goal[5] = -pi
x_goal[6] = pi/2
add_state_eq!(traj_data, xi -> xi - x_goal, N)

traj = BilevelTrajOpt.trajopt_snopt(traj_data)

Finished successfully: optimality conditions satisfied


22×10 Array{Float64,2}:
  0.0      0.0228792   0.032508   …    0.0812889    0.0        0.0     
 -1.5708  -0.883833    0.0260361       2.00818      1.5708     1.5708  
  0.0     -0.0370493  -0.180099       -0.095391     0.0        0.0     
  0.0      0.847657    1.5708          0.96406      0.0        0.0     
  0.0      0.0721667   0.077659       -2.99871     -3.14159   -3.14159 
  1.5708   1.60907     2.0303     …    2.29999      1.5708     1.5708  
  0.0     -0.138476   -0.591951       -0.0438368    0.0        0.0     
  0.0      0.457584    0.192576        0.924309    -1.62578    0.0     
  0.0     13.7393     18.1974         -4.8414      -8.74775    0.0     
  0.0     -0.740985   -2.861           6.79407      1.90782    0.0     
  0.0     16.9531     14.4628     …  -12.9767     -19.2812     0.0     
  0.0      1.44333     0.109847      -10.2281      -2.8577     0.0     
  0.0      0.765558    8.42459       -11.2783     -14.5839     0.0     
  0.0     -2.76953    -9.06948         8

In [12]:
t = cumsum([Δt for i in 1:N]);
q = [traj[1:num_positions(mechanism),i] for i in 1:N]
setanimation!(mvis, t, q)

In [63]:
# robust version adds a "worst case scenario" computation for "wind gust" on the plate

# wind is more horizontal than vertical
w_max = 1.
w_z_max = .2
c_max = .3

plate_body = findbody(mechanism, "panda_link8")
plate_frame = default_frame(plate_body)
plate_normal = [0.,0.,1.]

world_frame = root_frame(mechanism)

function c_wind(q::AbstractArray{T}) where T
    state = MechanismState{T}(mechanism)
    set_configuration!(state, q)
    trans = relative_transform(state, plate_frame, world_frame)
    pn = (trans.mat' * vcat(plate_normal,1.))[1:3]
    display(pn)
    
    fw = w -> -(w'*pn)
    hw = w -> [0.]
    gw = w -> [sum(w.^2) - w_max^2, w[3] - w_z_max, -w_z_max - w[3]]
    w0 = zeros(3)
    λ0 = zeros(1)
    μ0 = zeros(3)
    
    wsol,λsol,μsol,Lsol = auglag_solve(w0,λ0,μ0,fw,hw,gw,inplace=false)
    display(wsol)
    
    wsol'*pn - c_max
end

# traj_data = get_traj_data(mechanism,env,Δt,N,false)

# x_start = zeros(traj_data.num_q+traj_data.num_v)
# x_start[2] = -pi/2
# x_start[6] = pi/2
# add_state_eq!(traj_data, xi -> xi - x_start, 1)

# x_goal = zeros(traj_data.num_q+traj_data.num_v)
# x_goal[2] = pi/2
# x_goal[5] = -pi
# x_goal[6] = pi/2
# add_state_eq!(traj_data, xi -> xi - x_goal, N)

# add_fn_ineq!(traj_data, c_wind, 5)

# traj = BilevelTrajOpt.trajopt_snopt(traj_data)

# q = traj[1:traj_data.num_q,1]
q = [-pi/2, pi/2, 0., 0., 0., 0., 0.]
display(q)
c_wind(q)

7-element Array{Float64,1}:
 -1.5707963267948966
  1.5707963267948966
  0.0               
  0.0               
  0.0               
  0.0               
  0.0               

3-element Array{Float64,1}:
 -1.0                  
 -4.896699882521141e-12
  4.896588860074816e-12

3-element Array{Float64,1}:
 -0.5055682506777173    
 -2.4964191117114556e-12
 -1.3721858442369174e-12

0.20556825067771728