In [6]:
using Revise
using Bilevel

In [25]:
z0 = rand(4)*200. - 100.

4-element Array{Float64,1}:
  88.7849  
   0.231532
 -14.58    
 -10.5938  

In [37]:
function f(a)
    n = Int(sqrt(length(a)))
    A = reshape(a,n,n)
    U,s,V = svd(A)
    return vcat(U[:],s[:],V[:])
end

sol = f(z0)

# autodiff 
J_auto = ForwardDiff.jacobian(f,z0)

# # numerical
ϵ = 1e-8
J_num = zeros(size(J_auto))
for i = 1:length(z0)
    δ = zeros(length(z0))
    δ[i] = ϵ
    J_num[:,i] = (f(z0 + δ) - sol)/ϵ
end

display(sol)
display(J_auto)
display(J_num)

err = maximum(abs.(J_auto - J_num))
display(err)

10-element Array{Float64,1}:
 -0.99976  
 -0.0219076
 -0.0219076
  0.99976  
 89.9954   
 10.4138   
 -0.986369 
  0.164549 
 -0.164549 
 -0.986369 

10×4 Array{Float64,2}:
 -1.00285e-5    0.000243209  -2.72655e-5  -4.12069e-5 
  0.000457656  -0.0110989     0.00124427   0.00188049 
  0.000457656  -0.0110989     0.00124427   0.00188049 
  1.00285e-5   -0.000243209   2.72655e-5   4.12069e-5 
  0.986132      0.0216089    -0.164509    -0.00360486 
  0.00360486   -0.164509      0.0216089   -0.986132   
 -0.000309507   0.000204792  -0.00182675  -7.53248e-5 
 -0.00185531    0.0012276    -0.0109503   -0.000451526
  0.00185531   -0.0012276     0.0109503    0.000451526
 -0.000309507   0.000204792  -0.00182675  -7.53248e-5 

10×4 Array{Float64,2}:
 -1.00475e-5    0.000243183  -2.72671e-5  -4.12004e-5
  0.000457655  -0.0110989     0.00124427   0.00188049
  0.000457654  -0.0110989     0.00124427   0.00188049
  1.00031e-5   -0.000243205   2.72671e-5   4.11893e-5
  0.98613       0.0216076    -0.164511    -0.00360671
  0.00360512   -0.164509      0.0216092   -0.986132  
 -0.000309486   0.000204792  -0.00182675  -7.53064e-5
 -0.0018553     0.00122761   -0.0109503   -0.00045153
  0.0018553    -0.00122761    0.0109503    0.00045153
 -0.000309486   0.000204792  -0.00182675  -7.53064e-5

2.6519532247970545e-6